name: format the code
on: [push]
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Install packages
        run: npm i
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
